### ISSUE TITLE
RenderMudDatePicker Attribute doesn't seem to work

### ISSUE THREAD

**Issue by henon** [CodeGator/CG.Blazor.Forms._MudBlazor#2]
```
public class MudBlazorVM {
        [RenderMudDatePicker]
        public DateTime? DateOfBirth { get; set; }
}
```

doesn't seem to render anything. 

As a side note, it would be awesome if the Submit button could be configured with a `RenderFragment`

**Comment by martycook** [comment]
The date picker problem is fixed. Thanks for bringing that to my attention.

The notion of using a RenderFragment for the submit button is quite interesting. I'll give that some thought.
